project:
  type: website
  output-dir: _site

execute:
  freeze: auto

render:
    - index.qmd
    - setup.qmd
    - agenda/agenda.qmd
    - slides.qmd
    - notebooks/1_introduction.qmd
    - notebooks/1_1_MathematicalFramework/DynamicalSystems.qmd
    - notebooks/2_fair_model.qmd
    - notebooks/02a_mean_field_models.qmd
    - notebooks/02b_coupled_networks.qmd
    - notebooks/3_dynamics.qmd
    - notebooks/03_bifurcation_analysis.qmd
    - notebooks/4_optimization.qmd
    - notebooks/04a_alzheimer_usecase.qmd
    - notebooks/04b_parameter_fitting.qmd
    - notebooks/5_stimulation.qmd
    - notebooks/05_stimulation.qmd

website:
  title: "Brainsimulation Workshop"
  description: "Towards translational and mechanistic whole-brain simulations with The Virtual Brain"
  site-url: "https://virtual-twin.github.io/Brain-Simulation-Workshop"
  repo-url: "https://github.com/virtual-twin/Brain-Simulation-Workshop"
  repo-actions: [edit, issue]
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    logo: img/logo.png
    background: light
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Setup
      - href: agenda/agenda.qmd
        text: Agenda
      - href: slides.qmd
        text: Slides
      - text: Notebooks
        menu:
          - href: notebooks/1_introduction.qmd
            text: "1. Introduction to Brain Network Modelling"
          - href: notebooks/1_1_MathematicalFramework/DynamicalSystems.qmd
            text: "  1.1 Mathematical Framework"
          - text: "---"
          - href: notebooks/2_fair_model.qmd
            text: "2. Defining a FAIR model"
          - href: notebooks/02a_mean_field_models.qmd
            text: "  2.1 Mean field models"
          - href: notebooks/02b_coupled_networks.qmd
            text: "  2.2 Coupled networks"
          - text: "---"
          - href: notebooks/3_dynamics.qmd
            text: "3. Dynamical perspective"
          - href: notebooks/03_bifurcation_analysis.qmd
            text: "  3.1 Bifurcation analysis"
          - text: "---"
          - href: notebooks/4_optimization.qmd
            text: "4. Parameter optimisation"
          - href: notebooks/04a_alzheimer_usecase.qmd
            text: "  4.1 Alzheimer use case"
          - href: notebooks/04b_parameter_fitting.qmd
            text: "  4.2 Parameter fitting"
          - text: "---"
          - href: notebooks/5_stimulation.qmd
            text: "5. Stimulating the brain"
          - href: notebooks/05_stimulation.qmd
            text: "  5.1 Stimulation"
    right:
      - icon: github
        href: "https://github.com/virtual-twin/Brain-Simulation-Workshop"
        aria-label: GitHub
  sidebar:
    - title: "Notebooks"
      style: docked
      contents:
        - setup.qmd
        - notebooks/1_introduction.qmd
        - section: "1.1 Mathematical Framework"
          contents:
            - notebooks/1_1_MathematicalFramework/DynamicalSystems.qmd
        - section: "2. Defining a FAIR model"
          href: notebooks/2_fair_model.qmd
          contents:
            - notebooks/02a_mean_field_models.qmd
            - notebooks/02b_coupled_networks.qmd
        - section: "3. Dynamical perspective"
          href: notebooks/3_dynamics.qmd
          contents:
            - notebooks/03_bifurcation_analysis.qmd
        - section: "4. Parameter optimisation"
          href: notebooks/4_optimization.qmd
          contents:
            - notebooks/04a_alzheimer_usecase.qmd
            - notebooks/04b_parameter_fitting.qmd
        - section: "5. Stimulating the brain"
          href: notebooks/5_stimulation.qmd
          contents:
            - notebooks/05_stimulation.qmd
  page-footer:
    left: "© 2026 TVB Workshop. Charité University Medicine Berlin and Berlin Institute of Health."
    center: |
      [![Charité](/img/Charite.png){fig-alt="Charité" height="40px"}](https://www.charite.de)
      &nbsp;&nbsp;
      [![BIH](/img/BIH.png){fig-alt="BIH" height="40px"}](https://www.bihealth.org)
      &nbsp;&nbsp;
      [![BSS](/img/BSS.png){fig-alt="BSS" height="40px"}](https://www.berlin-school-of-mind-and-brain.de)
      &nbsp;&nbsp;
      [![EBRAINS](/img/EBRAINS.svg){fig-alt="EBRAINS" height="40px"}](https://ebrains.eu)
    right:
      - icon: github
        href: "https://github.com/virtual-twin/tvb-ontology-optim-workshop"

bibliography: bibliography.bib
link-external-newwindow: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    highlight-style: github
  ipynb:
    toc: true
    toc-depth: 3



authors:
  - name: "Leon Stefanovski"
    affiliation:
       - ref: charite
  - name: "Marius Pille"
    affiliation:
       - ref: bih
  - name: "Leon Martin"
    affiliation:
       - ref: bih
affiliations:
  - id: charite
    name: "Charité University Medicine Berlin"
  - id: bih
    name: "Berlin Institute of Health at Charité University Medicine"